#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

##Color settings
# bspc config focused_border_color "#025db7"
# bspc config focused_border_color "#1d99f3"
# bspc config normal_border_color "#1E222A"

# Pointer focus
# bspc config focus_follows_pointer true
# bspc config pointer_modifier super

#This creates and names desktops for multiple monitors.
# workspaces_multimonitor &
if [[ "$1" = 0 ]]; then
 if [[ $(xrandr -q | grep 'VGA1 connected') ]]; then
  xrandr --output LVDS1 --primary --mode 1366x768 --rotate normal --output VGA1 --mode 1280x1024 --rotate normal --left-of LVDS1
  bspc monitor LVDS1 -d 1 2 3 4 
  bspc monitor VGA1 -d 5
 else
  bspc monitor LVDS1 -d 1 2 3 4 5
 fi
fi


# bspc monitor LVDS1 -d 1 2 3 4 5
# bspc monitor VGA1 -d 6

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a Chromium desktop='^2'
bspc rule -a Brave-browser desktop='^2'
bspc rule -a TelegramDesktop desktop='^4' focus=on
bspc rule -a Geany desktop='^3' state=floating center=true rectangle=1000x625+0+0
bspc rule -a Code desktop='^3' state=floating center=true rectangle=1100x625+0+0
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Terminate already running polybar, eww, picom, sxhkd and dunst instances
processes=("picom" "sxhkd")

for process in "${processes[@]}"; do
 if pidof -q "$process"; then
  pkill -9 -x "$process" > /dev/null; sleep 0.1
 fi
done

# Launch picom // If you have old hardware or encounter problems 
# uncomment the picom "--legacy-backends" line and comment the current one.
#picom --config "$HOME"/.config/picom/picom.conf &
#picom --experimental-backends &
picom --legacy-backends --config "$HOME"/.config/bspwm/picom.conf &

# Set random wallpaper for actual rice
feh -z --no-fehbg --bg-fill Images/wall/

# Reload sxhkd daemon
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &

# Fix cursor
xsetroot -cursor_name left_ptr

# Polybar start
$HOME/.config/bspwm/polybar/launch.sh

# Rus lenguage
setxkbmap -option grp:alt_shift_toggle us,ru

